### ISSUE TITLE
MSAL logging improvements

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3028]
### Discussed in https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/discussions/3010

<div type='discussions-op-text'>

<sup>Originally posted by **bgavrilMS** November 12, 2021</sup>
Suggested improvements that can be made to MSAL logging: 

## Common log interface for MSAL/SAL/Wilson/MISE
- [x] https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3245

## Apps should not have to recompile to get verbose logs

- [x] Allow apps to change the logging verbosity based on an env variable (this will require a process restart)
- [x] Allow apps to change logging verbosity programmatically #2868 
- [ ] Allow apps to collect event logs, even if a logging callback has not been enabled (WithLogging + enable default logger already uses event source, but it's not turned on by default).

## Better logging in token caches
- [ ] Microsoft.Identity.TokenCache should reuse MSAL's logger 
- [x] The desktop cache should reuse MSAL's logger
- [x] Expose the correlation ID to token cache implementations #3008

## Logging perf
- [ ] Logging should not compute log strings unless the log level is met. 

## Add more info in the logs
- [x] #2029
- [x] Log important metrics irrespective of the log level #3004 

Additional discussion around logging: #1993 
</div>

**Comment by bgavrilMS** [comment]
This quarter we want to do only: 

- token cache logic uses MSAL loggers
- #2868

**Comment by jmprieur** [comment]
@bgavrilMS dynamically? you mean on AcquireTokenXXBuilder?

**Comment by bgavrilMS** [comment]
no, I mean: 

```csharp
...
.WithLogging(() =>_logLevel , LogCallback);

private static LogLevel _logLevel;

// apps monitor config or env changes
private void OnConfigChange()
{
    _logLevel = // read log level from config
}

```

**Comment by trwalke** [comment]
updating details with https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3245

**Comment by bgavrilMS** [comment]
This has not been completed.

**Comment by trwalke** [comment]
@bgavrilMS yeah, not sure how this got closed. Must a bug somewhere.

**Comment by bgavrilMS** [comment]
Tracking item for logging improvements.

**Comment by bgavrilMS** [comment]
T
