### ISSUE TITLE
[Feature Request] GA the WAM Integration with MSAL C++ Interop / Runtime 

### ISSUE THREAD

**Issue by gladjohn** [AzureAD/microsoft-authentication-library-for-dotnet#3375]
## Remaining work for GA

- [x]  [Bug - on some configurations msal_runtime.dll is not found](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/3964) (IN [PR](https://github.com/AzureAD/microsoft-authentication-library-for-cpp/pull/3397))
- [x] #3447 (design almost in final stages, this should be completed by end of feb 2023) (IN [PR](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/pull/3976))

- [x] [Product Backlog Item 1897893](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1897893) and #3772 
- [x] [Task 1903740](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1903740): Automated testing for MSAL .Net
- [x] [Product Backlog Item 1913500](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1913500): MSAL .NET Partner Integration testing (Several teams have this in production already, waiting for sign-off from VS)
- [x] #3613 (in code review)
- [x] #3788
- [x] #3685
- [x] #3740 
- [x] #3822
- [x] #3458
- [x] #3927
- [x] #3952
- [x] #3964
## Non-GA issues

- [x] #3772 
- [x] #3301 
- [ ] Add automated test to validate Wam Id in account in authResult [See](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/40157d950b7314e22a842303b8a58bdd9aaba231/tests/Microsoft.Identity.Test.Unit/PublicApiTests/PublicClientApplicationTests.cs#L857-L901)
- [x] #3961 (Will be fixed in the next MSAL release. [This is fixed in C++](https://github.com/AzureAD/microsoft-authentication-library-for-cpp/pull/3394))
- [ ] #3965
- [x] #3916 (Will be fixed in the next MSAL release. [This is fixed in C++](https://github.com/AzureAD/microsoft-authentication-library-for-cpp/pull/3394))

## Post-GA work

- [ ] #4006 (blocked feature needs to be added in MSAL C++ layer)

## External issues

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues?q=is%3Aissue+is%3Aopen+label%3Aexternal+label%3AWAM

## Cut

- [ ] ~[Product Backlog Item 1841040](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1841040): MsalRuntime - Windows Universal (UWP) support~ CUT. We'll use our old broker implementation on UWP.

- [ ] ~[Product Backlog Item 1842266](https://identitydivision.visualstudio.com/Engineering/_workitems/edit/1842266): Automated testing of .NET interop layer~ (Nice to have, but no user impact)

**Comment by bgavrilMS** [comment]
@GladwinJohnson @SameerK-MSFT - can we use this ticket to track overall progress for MsalRuntime integration (Win only)?

**Comment by bgavrilMS** [comment]
@gladjohn @SameerK-MSFT - can you please provide effort estimates for these?

**Comment by trwalke** [comment]
Added automate test task to epic

**Comment by pmaytak** [comment]
Closing, any other WAM bugs will be tracked by themselves.
