### ISSUE TITLE
[Feature Request] Improved dSTS support in MSAL

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#3789]
- [ ] End to end testing for client_credentials
- [ ] Manual test other flows
- [ ] Automation of other flows

**Comment by bgavrilMS** [comment]
Blocked until we have test resources from dSTS folks.
