### ISSUE TITLE
[Feature Request] Add support for STI 

### ISSUE THREAD

**Issue by bgavrilMS** [AzureAD/microsoft-authentication-library-for-dotnet#4060]
STI is a Microsoft internal token issuer. We want to support it client_credentials flow only, via extensibility. 

Proposed dev ex:

```csharp
var cca = ConfidentialClientApplicationBuilder.Create(client_id)
                        .WithGenericAuthority("https://sti_authority", tokenRequestContentType: ContentType.JSON ) 
                        .WithCacheOptions( extraTokenParamsToCache: new[] { "topology", "trusted_keys" }) 
                        .Build();

var authResult = cca.AcquireTokenForClient(new[] { scope })
     .OnBeforeTokenRequest( data => data.BodyParameters.Add("param1", "val1") ) // API exists today
     .ExecuteAsync();

```

This will require a few changes in MSAL: 

- [x] Ability to change the way MSAL does a POST request from UrlForms to JSON. Can be a parameter on `WithGenericAuthority`

Idea: could be interesting to have this on all authority. AAD should support this, MSAL did it at some point but stopped for reasons we don't know.

- [x] MSAL must be able to cache additional properties from the /token response. See `WithCacheOptions` proposal.
- [x] `AuthenticationResult.AdditionalResponseParameters` should expose the additional cached properties
- [x] Add support for non-scalar properties in `AuthenticationResult.AdditionalResponseParameters` (values can be JSON strings)

References: [fiddler trace of an STI req](https://microsofteur-my.sharepoint.com/:u:/g/personal/bogavril_microsoft_com/ESkuu7FCm_pLkb-IUagMrX8BUIBiCsWQbFnwKi6fIAKDAw?e=oxXza2)

**Comment by bgavrilMS** [comment]
@jmprieur @sruke - this is a design for the changes needed for MSAL to support STI. Please have a look and see what needs to be done for `ITokenAcquisition`.

**Comment by jmprieur** [comment]
LGTM, @bgavrilMS 
From the point of view of IdWeb, I would say there could propose a new interface in Id.Web like the following (it's just an idea, the types might not be right). This interface would be optional, but understood by TokenAcquisition.

```csharp
interface IIdentityProviderAdapter
{
 bool AppliesTo(string authority);
 void AdaptAppCreation(ConfidentialClientApplicationBuilder builder);
 void AdaptTokenAcquisition(AcquireTokenForClientBuilder builder);
}
```

The first party package extending MSAL and IdWeb would create new class StiAdapter that would implement this interface, in the way you proposed above, @bgavrilMS 


the STI clients would just add:

```csharp
services.AddStiAdapter();
```

which would really be a:

```csharp
services.AddSingleton<IIdentityProviderAdapter, StiAdapter>();
```

@jennyf19 what do you think?

**Comment by bgavrilMS** [comment]
@jmprieur, @jennyf19  - STI folks would like to partition the cache by resource as well. This is for S2S only.

Cache key today is: `clientId_tenantId_popKid`
Proposed cache key: `clientId_tenantId_resource_popKid`

I think it'd be easier to do this in MSAL, like `.WithCacheOptions(  IncludeResourceInAppTokenCacheKey=true ) ` and we can do it as part of this story. 

Or it can be done in Id.Web as well, but slightly more complex. Thoughts?

**Comment by bgavrilMS** [comment]
Other requirements which MSAL meets, but not sure about Id.Web and TokenAcquirer: 

- allow ephemeral POP keys (or more generally - custom POP keys / bring your own POP key)
- possibly a custom cache not based on Id.Web.TokenCache

**Comment by kevin-meyer** [comment]
I understand `WithGenericAuthority` is experimental at the moment, but I think a change may need to be made to the scope validation. I believe `ClientCredentialRequest.ExecuteAsync` is currently used which validates to ensure scopes are provided. Per OAuth 2.0 RFC, `scope` is optional when obtaining a token via client credentials. Please let me know if I'm misunderstanding something about the usage or intent of `WithGenericAuthority` feature.

**Comment by bgavrilMS** [comment]
@kevin-meyer - you are right, it is optional. 

 What IdP are you planning on using MSAL with that doesn't have scope? If it is STI, we can track it here. If it's something else, can you please log a bug ?

**Comment by kevin-meyer** [comment]
not STI. I’ll log a separate bug

**Comment by bgavrilMS** [comment]
Won't fix
