### ISSUE TITLE
[Epic]  Supportability: Add support for open telemetry to log client side data.

### ISSUE THREAD

**Issue by neha-bhargava** [AzureAD/microsoft-authentication-library-for-dotnet#4229]
- [ ]  Log data points to open telemetry which are currently [logged with ITelemetryClient](https://microsoft-my.sharepoint-df.com/:w:/p/nebharg/EWrRAFHR6VdGvx5i_-uCZiUBROlxzCXZzLdRUJ8ePTKkgw?e=RDxtgw)
- [ ] Capture metrics for success counter with tags client id, token source and cache refresh reason.
- [ ] Capture metrics for failure counter with tags client id, error code.
- [ ]  Add API to opt in to open telemetry.
- [ ] Add database to log the data points to.
- [ ] Create dashboards using the data logged.
